#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"loong64"}
SUFFIX="-${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

#if echo $TAG | grep -q dirty; then
#    TAG=dev
#fi

IMAGE=${REPO}/klipper-helm:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build --build-arg ARCH=${ARCH} -f ${DOCKERFILE} -t  cr.loongnix.cn/rancher/klipper-helm:v0.4.3 .
echo "Built cr.loongnix.cn/rancher/klipper-helm:v0.4.3"
